# TAGS: [ {name} {uuid} {admin} {whitelist_status} {whitelist_count} ]
Settings:
  use-permission: false
  permission: "whitelistplus.servername"
Messages:
  kick-message: "&9Whitelist&8> &c&oConnection failed: &8&l--&a&l> &cNot Whitelisted, &c&n{name}"
  whitelist-alert: "&6Alert&7&l> &6&l{name}, &7is not Whitelisted!"
  enforce-kick: "&4Server whitelist was enforced by an Admin!"
  enforce: "&4{admin}> &7whitelist enforce success!"
  whitelist: "&aServer is whitelisted!"
  no-whitelist: "&cServer isnt whitelisted!"
  status: "&bWhitelist Status\n{whitelist_status}\n&7Whitelisted players: &b{whitelist_count}"
permission-messages:
  command: "&cWhitelist access requires staff permissions."
  argument-error: "&7Error with command argument passed."
  config-reload: "&7You reloaded whitelist config!"