name: WhitelistPlus
main: me.signifies.github.io.Whitelistplus
version: 2.0
description: A better whitelist management system.
author: Signifies
website: https://signifies.github.io/

commands:
  whitelistmsg:
    description: Set a custom whitelist messaqge on the fly.
    aliases: [wlm,whitelistm,wm]
  whitelistplus:
    description: Manage server whitelist with custom features.
    aliases: [wlp,wp]

permissions:
  customwhitelist.*:
    description: Gives complete access to all permissions.
    children:
      customwhitelist.setkickmsg: true
      customwhitelist.reload: true
      customwhitelist.cmd: true
      customwhitelist.enforce.bypass: true
      customwhitelist.enforce: true
      customwhitelist.notify: true
      customwhitelist.whitelist.override: true

  customwhitelist.mod:
    description: Gives general mod access.
    children:
      customwhitelist.cmd: true
      customwhitelist.enforce.bypass: true
      customwhitelist.enforce: true
      customwhitelist.notify: true
      customwhitelist.whitelist.override: true