name: WhitelistPlus
main: me.signifies.birb.WhitelistPlus
version: 1.2
description: A better whitelist management system.
author: Signifies
website: wwww.github.com/Signifies/whitelistplus

commands:
  whitelistmsg:
    description: Set a custom whitelist messaqge on the fly.
    aliases: [wlm,whitelistm,wm]
  whitelistplus:
    description: Manage server whitelist with custom features.
    aliases: [wlp,wp]
